export const cartConstants = {
    ADD_REQUEST: 'CART_ADD_REQUEST',
    ADD_SUCCESS: 'CART_ADD_SUCCESS',
    ADD_FAILURE: 'CART_ADD_FAILURE',

    DELETE_REQUEST: 'CART_DELETE_REQUEST',
    DELETE_SUCCESS: 'CART_DELETE_SUCCESS',
    DELETE_FAILURE: 'CART_DELETE_FAILURE',

    CLEAR_REQUEST: 'CART_CLEAR_REQUEST',
    CLEAR_SUCCESS: 'CART_CLEAR_SUCCESS',
    CLEAR_FAILURE: 'CART_CLEAR_FAILURE',

    GET_CART_REQUEST: 'CART_GET_REQUEST',
    GET_CART_SUCCESS: 'CART_GET_SUCCESS',
    GET_CART_FAILURE: 'CART_GET_FAILURE',
    
    // GET_ITEMS_COUNT_REQUEST: 'CART_GET_ITEMS_COUNT_REQUEST',
    // GET_ITEMS_COUNT_SUCCESS: 'CART_GET_ITEMS_COUNT_SUCCESS',
    // GET_ITEMS_COUNT_FAILURE: 'CART_GET_ITEMS_COUNT_FAILURE',
};
