export const cartItemConstants = {
    ADD_REQUEST: 'USERS_LOGIN_REQUEST',
    ADD_SUCCESS: 'USERS_LOGIN_SUCCESS',
    ADD_FAILURE: 'USERS_LOGIN_FAILURE',

    DELETE_REQUEST: 'USER_SIGNUP_REQUEST',
    DELETE_SUCCESS: 'USER_SIGNUP_SUCCESS',
    DELETE_FAILURE: 'USER_SIGNUP_FAILURE',

    CLEAR_REQUEST: 'USER_SIGNUP_REQUEST',
    CLEAR_SUCCESS: 'USER_SIGNUP_SUCCESS',
    CLEAR_FAILURE: 'USER_SIGNUP_FAILURE',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',
};
