export const productConstants = {
    ADD_REQUEST: 'PRODUCT_ADD_REQUEST',
    ADD_SUCCESS: 'PRODUCT_ADD_SUCCESS',
    ADD_FAILURE: 'PRODUCT_ADD_FAILURE',

    UPDATE_REQUEST: 'PRODUCT_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'PRODUCT_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'PRODUCT_UPDATE_FAILURE',

    REMOVE_REQUEST: 'PRODUCT_REMOVE_REQUEST',
    REMOVE_SUCCESS: 'PRODUCT_REMOVE_SUCCESS',
    REMOVE_FAILURE: 'PRODUCT_REMOVE_FAILURE',

    GETALL_REQUEST: 'PRODUCTS_GETALL_REQUEST',
    GETALL_SUCCESS: 'PRODUCTS_GETALL_SUCCESS',
    GETALL_FAILURE: 'PRODUCTS_GETALL_FAILURE',
};
